# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{5e16de74-e86c-4cb7-a6b1-58333af71cb7}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=feeds'],
        'esModule': 'resource:///modules/AboutFeeds.sys.mjs',
        'constructor': 'AboutFeeds',
    },
]
